version: "3.4"
services:
  elasticsearch:
    image: elasticsearch:6.8.8
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - theHive-ElasticSearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  cortex:
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - "9001:9001"
    volumes:
      - theHive-CortexAnalyzers:/opt/Cortex-Analyzers
  thehive:
    image: thehiveproject/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "9000:9000"
    command: --cortex-port 9001
    volumes:
      - theHive-data:/etc/thehive
volumes:
  theHive-ElasticSearch:
    name: "theHive-ElasticSearch"
  theHive-CortexAnalyzers:
    name: "theHive-CortexAnalyzers"
  theHive-data:
    name: "theHive-data"