version: "3.4"
services:
  elasticsearch:
    image: elasticsearch:6.8.12
    restart: always
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - theHive-ElasticSearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  cortex:
    image: thehiveproject/cortex:3.0.1
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "9001:9001"
    volumes:
      - theHive-CortexAnalyzers:/opt/Cortex-Analyzers
      - theHive-CortexConfiguration:/etc/cortex/
      - theHive-MalpediaYara:/MalpediaYara
  thehive:
    image: thehiveproject/thehive:3.4.0
    restart: always
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "9000:9000"
    command: --cortex-port 9001
    volumes:
      - theHive-data:/etc/thehive
      - theHive-MalpediaYara:/MalpediaYara
volumes:
  theHive-ElasticSearch:
    name: "theHive-ElasticSearch"
  theHive-CortexAnalyzers:
    name: "theHive-CortexAnalyzers"
  theHive-data:
    name: "theHive-data"
  theHive-CortexConfiguration:
    name: "theHive-CortexConfiguration"
  theHive-MalpediaYara:
    name: "theHive-MalpediaYara"  